Fix changes cleanup
vaimee/desmo-front pull request #22
Opened 2022-09-28 14:30 UTC by iosonopersia

Closes #17. Replaces #21.

The DesmoldSDK service gets almost completely rewritten.

A new page is shown when either Metamask isn't installed, the selected chain isn't Viviani or the user isn't logged in.
In each situation, a proper message is shown at the center of the page with an action button that allows the user to solve the problem in just a bit more than a click.

If the user didn't add the Viviani chain to its Metamask configuration, the button for switching to Viviani chain will also properly configure such chain.

Better error handling overall, with snackbar popups shown instead of using console.error (some errors can still appear in the console: they're thrown by Metamask itself).

Fixed the appearance of the two components in the TddManager page.

If the user changes chain or disconnects in the Metamask plugin, the page gets reloaded.
If the user changes account (wallet) in the Metamask plugin, the application handles this situation by updating dynamically its interfaces with the contracts.

2022-09-28 14:55 UTC, iosonopersia commented
**PLEASE, WAIT A LITTLE BIT BEFORE MERGING**

2022-09-30 08:59 UTC, relu91 commented
Checked the changes locally.
![image](https://user-images.githubusercontent.com/3170227/193233726-e1605f35-c7b7-4ce8-a616-da658674176e.png)

Does this mean that we can't verify that a similar RPC endpoint exists? Can't we just use the chainID? 

![image](https://user-images.githubusercontent.com/3170227/193233867-e4c31872-902d-4712-b187-72299f06463e.png)

I would remove the contract address from the title.

2022-09-30 09:14 UTC, iosonopersia commented
Yep, I didn't find a way to get a list of registered chains from Metamask, it's something which is missing from their API...
The only thing that can be done is to get the currently selected chainId: if it equals '0x85', then we don't even show that error page, otherwise we know it's not the Viviani chain (but we don't know if Viviani chain is registered anyway).

I can remove the contract address from the title, I'll do it immediately.

2022-09-30 09:17 UTC, iosonopersia commented
I removed the user address from the title.

2022-09-30 10:11 UTC, relu91 commented
from the metamask doc, there is an example how to first try switching and then ask for adding
```js
try {
  await ethereum.request({
    method: 'wallet_switchEthereumChain',
    params: [{ chainId: '0xf00' }],
  });
} catch (switchError) {
  // This error code indicates that the chain has not been added to MetaMask.
  if (switchError.code === 4902) {
    try {
      await ethereum.request({
        method: 'wallet_addEthereumChain',
        params: [
          {
            chainId: '0xf00',
            chainName: '...',
            rpcUrls: ['https://...'] /* ... */,
          },
        ],
      });
    } catch (addError) {
      // handle "add" error
    }
  }
  // handle other "switch" errors
}
```

2022-09-30 14:16 UTC, iosonopersia commented
I implemented the required behaviour.

2022-10-03 13:59 UTC, relu91 requested changes
The logic now is perfect. 

However, I still have these ugly messages:
![image](https://user-images.githubusercontent.com/3170227/193596126-a6628b1d-7dd4-43da-bbfe-da0fe3c421f1.png)

2022-10-03 16:03 UTC, merged